### PR TITLE
feat: add text background color

### LINKED ISSUE #6: Add text background color
First of all Thanks for this nice package !

any plan to support text background color ?
I can see it's for TODO and Widget is already there 

```
                    // TODO: Add text background color
                      // SizedBox(width: 20),
                      // TextBackgroundColor(),
```

### PR DESCRIPTION
**Pull request by mahdyar**
Closes #6 

How it looks like:

Screen Recording 2021-08-15 at 3 58 43 PM

cc @mehdizarepour 

---

[`#iosh`](https://github.com/OSS-Hackathon/IranOpenSourceHackathon)

### CODE REVIEW

**Comment by mehdizarepour** [comment]
@mahdyar  Thanks for the PR.
Just consider every element on the editor must be customizable, If you look at the `EditorDecoration` you'll see all the tool widgets are customizable then please add the `textBackground` prop for this purpose.

**Comment by mahdyar** [comment]
> @mahdyar Thanks for the PR.
> Just consider every element on the editor must be customizable, If you look at the `EditorDecoration` you'll see all the tool widgets are customizable then please add the `textBackground` prop for this purpose.

hmm, should I get an Icon and the colors for the statuses or a widget and pass the status to it?

**Comment by mehdizarepour** [comment]
You can look at the `TextAlignment` widget as an example:

https://github.com/mehdizarepour/instagram-text-editor/blob/98969f0357043bfb5b32d708a569ed39a92c5a4f/lib/src/widget/text_alignment.dart#L5-L23

https://github.com/mehdizarepour/instagram-text-editor/blob/98969f0357043bfb5b32d708a569ed39a92c5a4f/lib/text_editor.dart#L134-L138

**Comment by mahdyar** [comment]
> You can look at the `TextAlignment` widget as an example:
> 
> https://github.com/mehdizarepour/instagram-text-editor/blob/98969f0357043bfb5b32d708a569ed39a92c5a4f/lib/src/widget/text_alignment.dart#L5-L23
> 
> https://github.com/mehdizarepour/instagram-text-editor/blob/98969f0357043bfb5b32d708a569ed39a92c5a4f/lib/text_editor.dart#L134-L138

Well, which part of it should be customizable? the icon? text style? default background color?

**Comment by mehdizarepour** [comment]
The appearance of the `TextBackgroundColor` widget, Developers must be able to change the appearance of the widget. Take a look at this [Example](https://github.com/mehdizarepour/instagram-text-editor/blob/master/example/lib/main.dart#L91):

```diff
TextEditor(
  fonts: fonts,
  text: text,
  textStyle: textStyle,
  textAlingment: textAlign,
  minFontSize: 10,
+ decoration: EditorDecoration(
+  doneButton: Icon(Icons.close, color: Colors.white),
+  fontFamily: Icon(Icons.title, color: Colors.white),
+  colorPalette: Icon(Icons.palette, color: Colors.white),
+  alignment: AlignmentDecoration(
+   left: Text(
+       'left',
+       style: TextStyle(color: Colors.white),
+     ),
+     center: Text(
+       'center',
+       style: TextStyle(color: Colors.white),
+     ),
+     right: Text(
+       'right',
+       style: TextStyle(color: Colors.white),
+     ),
+   ),
+ ),
  onEditCompleted: (style, align, text) {
    setState(() {
      _text = text;
      _textStyle = style;
      _textAlign = align;
    });
    Navigator.pop(context);
  },
);
```

**Comment by mehdizarepour** [comment]
Also, there is and another issue with your PR too, It doesn't behave like Instagram background feature.
On Instagram text editor when you change the color it changes the text color depending on the color that we've chosen.

https://user-images.githubusercontent.com/8446770/129669428-19ca895b-ef09-4944-b37d-221307fb555c.MP4


There are two options in Instagram for background, When we choose text color and then the background will change to match the text color and vice versa.

**Comment by mahdyar** [comment]
> The appearance of the `TextBackgroundColor` widget, Developers must be able to change the appearance of the widget. Take a look at this [Example](https://github.com/mehdizarepour/instagram-text-editor/blob/master/example/lib/main.dart#L91):
> 
> ```diff
> TextEditor(
>   fonts: fonts,
>   text: text,
>   textStyle: textStyle,
>   textAlingment: textAlign,
>   minFontSize: 10,
> + decoration: EditorDecoration(
> +  doneButton: Icon(Icons.close, color: Colors.white),
> +  fontFamily: Icon(Icons.title, color: Colors.white),
> +  colorPalette: Icon(Icons.palette, color: Colors.white),
> +  alignment: AlignmentDecoration(
> +   left: Text(
> +       'left',
> +       style: TextStyle(color: Colors.white),
> +     ),
> +     center: Text(
> +       'center',
> +       style: TextStyle(color: Colors.white),
> +     ),
> +     right: Text(
> +       'right',
> +       style: TextStyle(color: Colors.white),
> +     ),
> +   ),
> + ),
>   onEditCompleted: (style, align, text) {
>     setState(() {
>       _text = text;
>       _textStyle = style;
>       _textAlign = align;
>     });
>     Navigator.pop(context);
>   },
> );
> ```

Just to be clear, is this what you mean?
```diff
TextEditor(
  fonts: fonts,
  text: text,
  textStyle: textStyle,
  textAlingment: textAlign,
  decoration: EditorDecoration(
    doneButton: Icon(Icons.close, color: Colors.white),
    fontFamily: Icon(Icons.title, color: Colors.white),
    colorPalette: Icon(Icons.palette, color: Colors.white),
    alignment: AlignmentDecoration(
      left: Text(
        'left',
        style: TextStyle(color: Colors.white),
      ),
      center: Text(
        'center',
        style: TextStyle(color: Colors.white),
      ),
      right: Text(
        'right',
        style: TextStyle(color: Colors.white),
      ),
    ),
+   textBackgroundColor: TextBackgroundColorDecoration(
+      enable: ...
+      exchange: ...
+      none: .....
+    ),
  ),
),
```


> Also, there is and another issue with your PR too, It doesn't behave like Instagram background feature.
> On Instagram text editor when you change the color it changes the text color depending on the color that we've chosen.
> RPReplay_Final1629178228.MP4
> 
> There are two options in Instagram for background, When we choose text color and then the background will change to match the text color and vice versa.

I'm on it! :)

**Comment by mehdizarepour** [comment]
> Just to be clear, is this what you mean?

Yeah, Just use `disable` instead of `none` (Because there is a background button but it's not enabled) and `TextBackgroundDecoration` for the decorator class because maybe we add texture to the background in the future.

**Comment by mehdizarepour** [comment]
I've tested your update, It has caused a new issue, If you change the text color two or three times, It will be transparent.
I didn't write any test for this package, Please test your code before sending updates, thanks.

**Comment by mahdyar** [comment]
> I've tested your update, It has caused a new issue, If you change the text color two or three times, It will be transparent.
> I didn't write any test for this package, Please test your code before sending updates, thanks.

Fixed in 36180ad.

**Comment by mehdizarepour** [comment]
@mahdyar, First of all, thank you for this PR.
I've reviewed your code, you didn't adhere to standards that are compatible with the rest of the package's code. For example, `Provider` has been used to manage the states of the package, not the `setState` function and some other standards. I want the code to stay clean then instead of telling all the points to you, I preferred to fix this issue by myself (Your `lightenColor` helped a lot).

Then I'm gonna close this PR, Thank you for your time.

**Comment by mahdyar** [comment]
> @mahdyar, First of all, thank you for this PR.
> I've reviewed your code, you didn't adhere to standards that are compatible with the rest of the package's code. For example, `Provider` has been used to manage the states of the package, not the `setState` function and some other standards. I want the code to stay clean then instead of telling all the points to you, I preferred to fix this issue by myself (Your `lightenColor` helped a lot).
> 
> Then I'm gonna close this PR, Thank you for your time.

Actually that's your own code [[+](https://github.com/mehdizarepour/instagram-text-editor/blame/0bb404953526de8498199216cbc417e603c14fea/lib/src/widget/text_background_color.dart#L17)], and I had nothing to do with it. besides that, It would have been much better if you've told that at the first place instead of mentioning issues.

**Pull request closed without merging**
